/*
 * This source file was generated by the Gradle 'init' task
 */
package sa_id_validation;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        System.out.print("Enter South African ID number: ");
        String id = scanner.nextLine();
        System.out.println("========================================");
        System.out.println("      South African ID Validation");
        System.out.println("========================================");
        System.out.printf("ID Number   : %s\n", id);
        ValidateSaId.ValidationResult result = ValidateSaId.validateIdNumber(id);
        if (result.valid) {
            System.out.println("Status      : VALID\n");
            System.out.println("Details:");
            System.out.printf("  - Date of Birth : %s\n", result.birthdate);
            System.out.printf("  - Gender        : %s\n", result.gender);
            System.out.printf("  - Citizenship   : %s\n", result.citizenship);
            System.out.printf("  - Age           : %d\n", result.age);
        } else {
            System.out.println("Status      : INVALID\n");
            System.out.println("Reason:");
            System.out.printf("  - %s\n", result.reason);
        }
        System.out.println("========================================");
        scanner.close();
    }
}